news/urls.py
from django.urls import path

from . import views

app_name = 'news'


urlpatterns = [
    path('', views.news_list, name='list',),
    path('<int:id>/', views.news_detail, name='detail'),
]

tutorial_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
]

core/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models


class Post(models.Model):
    name = models.CharField('Название', max_length=256)
    content = models.TextField('Контент')
    image = models.ImageField('Изображение', upload_to='news/', null=True, blank=True)
    date_created = models.DateField('Дата публикации')
    tags = models.ManyToManyField('Tag', verbose_name='Теги')

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.name


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.CharField(max_length=256)
    text = models.TextField()
    date = models.DateField()

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'{self.author} - {self.date}'


class Tag(models.Model):
    name = models.CharField(max_length=256)

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def __str__(self):
        return self.name

core/views.py
from django.shortcuts import render


def home():
    pass


def contacts():
    pass

news/views.py
from django.shortcuts import render

from .models import Post


def news_list(request):
    posts = Post.objects.all()
    ctx = {
        'posts': posts,
    }
    return render(request, 'news/list.html', ctx)


def news_detail(request, id):
    post = Post.objects.get(id=id)
    ctx = {
        'post': post,
    }
    return render(request, 'news/detail.html', ctx)

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Главная страница</h1>
</body>
</html>

<script>
    var table = document.getElementById('table');
    table.appendChild('<li>'+ response +'</li>');
</script>

templates/news/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


    <h1>{{ post }}</h1>

    <p>
        {{ post.content }}
    </p>

    <em>{{ post.date_created }}</em><br>

    <a href="{% url 'news:list' %}">Назад</a>
    <hr>


</body>
</html>

templates/news/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    {% for post in posts %}

        <h1>{{ post }}</h1>

        <p>
            {{ post.content }}
        </p>

        <em>{{ post.date_created }}</em><br>

        <a href="{% url 'news:detail' post.id %}">Читать далее</a>
        <hr>
    {% endfor %}


</body>
</html>